---
title: "calculating life cycle dates"
output: html_document
---

```{r}
#this is 2023 data
wild_wm <- read.csv(here("data", "raw data", "processedwm.csv"))
```

```{r}
hist(wild_wm$BudBurstDay)

#to calculate median hatch date, use the median budbusrt date as a proxy
median(wild_wm$BudBurstDay, na.rm = TRUE)
as.Date(109.5497 - 1, origin = "2023-01-01")
#median budburst/hatch date was 19th april

#to calculate median pupation date, use CatHalfDay (half of the caterpillars descending from the trees) as a proxy
median(wild_wm$CatHalfDay, na.rm = TRUE)
as.Date(145.9418 - 1, origin = "2023-01-01")
#median cat half day was the 25th may

#this gives 36 days between hatching and pupation
#my estimates from the ambient treatment, although the dates are slightly earlier, have 35 days from hatching to pupation.

#to calculate median emergence date use moth peak day
median(wild_wm$MothPeakDay, na.rm = TRUE)
as.Date(343.129 - 1, origin = "2023-01-01")
#median emergence date was the 9th december
#if we assume winter moths live 30 days (that's a generous estimate) then resource allocation ens on the 8th January
#this gives rhe resource allocation period as between the 25th may and the 8th january, which is 229 days
#the resource allocation period of my ambient ambient groups was between the 16th may and the 29th december, which is 227 days
```

```{r}
#now i want to calculate the mean temperature in each treatment during resource acquisition and resource allocation
incubator_treatments <- read.csv(here("data", "raw data", "mbiols_daily_temperature_data.csv"))

#to make sure dates are stored as dates, and temperatures as numbers
incubator_treatments <- incubator_treatments %>%
  mutate(
    date_1   = as.Date(date_1, format = "%d/%m/%Y"),
    date_end = as.Date(date_end, format = "%d/%m/%Y"),
    `plus2.5`    = as.numeric(`plus2.5`),
    `plus1.5`    = as.numeric(`plus1.5`),
    `actual.mean` = as.numeric(`actual.mean`),
    `minus1.5`   = as.numeric(`minus1.5`),
    `minus2.5`   = as.numeric(`minus2.5`)
  )
#combine date 1 and date end into one date column
incubator_treatments <- incubator_treatments %>%
  group_by(date_1, date_end, Hour_group) %>%
   pivot_longer(
    cols = c(date_1, date_end),
    names_to = "date_type",
    values_to = "date") 

#RESOURCE ACQUISITION PERIOD
#filter for the resource allocation period - between the 19th april and the 25th may
acquisition_period <- incubator_treatments %>%
  filter(date >= as.Date("2025-04-19") & date <= as.Date("2025-05-25"))

#now calculate the mean in each incubator during the allocation period
mean(acquisition_period$minus1.5)
#cool = 9.37

mean(acquisition_period$actual.mean)
#mean = 11.07

mean(acquisition_period$plus1.5)
#warm = 12.76

mean(acquisition_period$plus2.5)
#hot = 13.89



```

```{r}
#RESOURCE ALLOCATION PERIOD
#filter for the resource allocation period - between the 25th may 2025  and the 8th january 2026 
allocation_period <- incubator_treatments %>%
  filter(date >= as.Date("2025-05-25") & date <= as.Date("2026-01-08"))

#now calculate the mean in each incubator during the allocation period
mean(allocation_period$minus1.5)
#cool = 10.07

mean(allocation_period$actual.mean)
#mean = 12.08

mean(allocation_period$plus1.5)
#warm = 14.08

mean(allocation_period$plus2.5)
#hot = 15.54

```

