---
title: "calculating emergence date"
output: html_document
---

```{r}
emergence_dates <- read.csv(here("data", "raw data", "wild moths hatch dates.csv"))
```

```{r}
# Convert to Date
emergence_dates$capture_date <- as.Date(emergence_dates$capture_date, format = "%d/%m/%Y")

# Calculate median date
median_date <- median(emergence_dates$capture_date, na.rm = TRUE)
#median emergence date is the 28th november 2025
#one month after the emergence date is 28th december
```
```{r}
#hatch dates
#Median budburst = 99.333 - based on we only scored Rona's 18 transect trees
julian <- 99.333
year <- 2025

as.Date(julian - 1, origin = paste0(year, "-01-01"))
#median budburst was the 9th april 2025


#Median final instar WM half-fall = 130.455 - based on 80 of my trees across the woods 
julian <- 130.455
year <- 2025

as.Date(julian - 1, origin = paste0(year, "-01-01"))
#median final instar half-fall was the 10th may
```


```{r}
#now i want to calculate the mean temperature in each treatment during resource acquisition and resource allocation
incubator_treatments <- read.csv(here("data", "raw data", "mbiols_daily_temperature_data.csv"))

#to make sure dates are stored as dates, and temperatures as numbers
incubator_treatments <- incubator_treatments %>%
  mutate(
    date_1   = as.Date(date_1, format = "%d/%m/%Y"),
    date_end = as.Date(date_end, format = "%d/%m/%Y"),
    `plus2.5`    = as.numeric(`plus2.5`),
    `plus1.5`    = as.numeric(`plus1.5`),
    `actual.mean` = as.numeric(`actual.mean`),
    `minus1.5`   = as.numeric(`minus1.5`),
    `minus2.5`   = as.numeric(`minus2.5`)
  )
#combine date 1 and date end into one date column
incubator_treatments <- incubator_treatments %>%
  group_by(date_1, date_end, Hour_group) %>%
   pivot_longer(
    cols = c(date_1, date_end),
    names_to = "date_type",
    values_to = "date") 

#RESOURCE ACQUISITION PERIOD
#filter for the resource allocation period - between the 9th april and the 10th may
acquisition_period <- incubator_treatments %>%
  filter(date >= as.Date("2025-04-09") & date <= as.Date("2025-05-10"))

#now calculate the mean in each incubator during the allocation period
mean(acquisition_period$minus1.5)
#cool = 7.842

mean(acquisition_period$actual.mean)
#mean = 9.599

mean(acquisition_period$plus1.5)
#warm = 11.356

mean(acquisition_period$plus2.5)
#hot = 12.523



```


```{r}
#RESOURCE ALLOCATION PERIOD
#filter for the resource allocation period - between the 10th may and the 25th may
allocation_period <- incubator_treatments %>%
  filter(date >= as.Date("2025-05-10") & date <= as.Date("2025-12-28"))

#now calculate the mean in each incubator during the allocation period
mean(allocation_period$minus1.5)
#cool = 10.267

mean(allocation_period$actual.mean)
#mean = 12.23952

mean(allocation_period$plus1.5)
#warm = 14.2079

mean(allocation_period$plus2.5)
#hot = 15.523

```
