---
title: "SEM"
output: html_document
---

STRUCTURAL EQUATION MODELLING

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(lme4)
library(MASS)
library(piecewiseSEM)
library(dplyr)
library(glmmTMB)
library(semEff)
```

```{r}
results <- read.csv(here("data", "clean data", "results.csv"), colClasses = c(sex = "character"))

#make maternal ID a factor
results$maternalID <- as.factor(results$maternalID)

#remove ambient, because these need to be modelled separately. also remove larval treatment of cool and mean, because the sample size isn't big enough to model - just not enough clutches.
#I think I will model the ambient larva treatment separately.
results_filtered <- results %>%
  filter(
    larval_treatment %in% c("warm", "hot"),
    pupal_treatment != "ambient", clutch_size != 0) %>%
  mutate(numerical_pupal_treatment = case_when(
    pupal_treatment == "cool"  ~ 10.26702,
    pupal_treatment == "mean"  ~  12.23952,
    pupal_treatment == "warm"  ~  14.2079,
    pupal_treatment == "hot"   ~  15.523,
  )) %>% 
  mutate(numerical_larval_treatment = case_when(
    larval_treatment == "warm"  ~  11.35602,
    larval_treatment == "hot"   ~  12.523,
  )) %>%
  mutate(weight_mg = weight * 1000) %>%
  mutate(weight_mg_centered = weight_mg - mean(weight_mg, na.rm = TRUE)) %>%
  mutate(across(
    c(weight_mg, egg_mean_1A, clutch_size),
    ~ as.numeric(scale(.)),
    .names = "{.col}_z"
  ))


```

filtering the dataset
```{r}
#filter the dataset to just have the columns I need
sem_data <- results_filtered %>%
  dplyr::select(adultID, weight_mg, clutch_size, egg_mean_1A,
                numerical_larval_treatment, numerical_pupal_treatment,
                maternalID) %>%
  filter(!is.na(egg_mean_1A))

#to do some sense checks on the model predictions
#get the mean clutch size from warm and hot treatments
results_warm <- sem_data %>%
  filter(numerical_larval_treatment == 11.35602)
mean(results_warm$clutch_size)
#109


results_hot <- sem_data %>%
  filter(numerical_larval_treatment == 12.523)
mean(results_hot$clutch_size)
#139

#the total effect of larval treatment on clutch size is 0.22
#exp(0.22) = 1.246077
#this means for every 1 degree of warming the moths lay ~25% more eggs, mediated through female mass
#from warm to hot there is 13.89 - 12.76 = 1.13 degrees of warming
#109 x 1.13 x 1.246077 = 153
#109 x 1.246077 = 135
#these estimates are pretty close to what we actually saw in the hot treatment
```

fitting the psem model
```{r}
# individual models to go into the psem
m_model <- lm(weight_mg ~ numerical_larval_treatment + numerical_pupal_treatment,
              data = sem_data)

y_model <- glm.nb(clutch_size ~ numerical_larval_treatment + numerical_pupal_treatment + weight_mg, data = sem_data)

x_model <- lmer(egg_mean_1A ~ numerical_pupal_treatment + numerical_larval_treatment + clutch_size + weight_mg + (1|maternalID), data = sem_data)

# SEM with correlated error between clutch size and egg size
sem_model <- psem(
  m_model,
  y_model,
  x_model,
  clutch_size %~~% egg_mean_1A   # this adds the correlated residual
)

#check model assumptions
plot(y_model)

# Summary with standardized coefficients
summary(sem_model, standardize = "scale",  conserve = TRUE) 

#standardised coefficients
coefs(sem_model, standardize = "scale", standardize.type = "Menard.OE")

# Plot standardized SEM
plot(sem_model, show = "std", digits = 2)


```


```{r}
#use the semEff package to get standardised effects and confidence intervals
#set.seed(123)
#standardised_effects <- semEff(sem_model,R = 10000, ran.eff = "maternalID")

standardised_effects <- readRDS("~/University stuff/Year 4/results/R project/data/clean data/standardised_effects.rds")


summary(standardised_effects)

print(standardised_effects)

#save the standardised effects so I don't have to re-run the bootstrap every time
#saveRDS(
# standardised_effects,
 #file = here("data", "clean data", "standardised_effects.rds")
#)
```



```{r}
#to get unstandardised (raw) coefficients
#set.seed(123)

#effects <- bootEff(sem_model, R = 10000, ran.eff = "maternalID", incl.raw = TRUE) 
#raw_effects <- semEff(effects, use.raw = TRUE)

#saveRDS(raw_effects, file = here("data", "clean data", "raw_effects.rds"))


raw_effects <- readRDS("~/University stuff/Year 4/results/R project/data/clean data/raw_effects.rds")

summary(raw_effects)

#

```

now I want to generate model predictions so that I can plot them
```{r}
#bootstrap estimates for the model
#sem.boot <- bootEff(sem_model, R = 10000, seed = 123, ran.eff = "maternalID")

#save this so i don't have to re-run this bootstrap every single time
#saveRDS(sem.boot, file = here("data", "clean data", "sem.boot.rds"))

#now read in the bootstrapped estimates for the model, that i saved earlier
sem.boot <- readRDS("~/University stuff/Year 4/results/R project/data/clean data/sem.boot.rds")


#use the bootstrap estimates to calculate effects and confidence intervals
sem.eff <- semEff(sem.boot)
#summary(sem.eff)
```


```{r}
#get predicted total effects for clutch size
tot <- getTotEff(sem.eff, "clutch.size")
tot.b <- getTotEff(sem.eff, "clutch.size", type = "boot")

#get the predicted direct effects for clutch size
dir    <- getDirEff(sem.eff, "clutch.size")
dir.b  <- getDirEff(sem.eff, "clutch.size", type = "boot")

#get the predicted indirect effects for clutch size
ind    <- getIndEff(sem.eff, "clutch.size")
ind.b  <- getIndEff(sem.eff, "clutch.size", type = "boot")

# fix names to match model - this fixed the problem that the model uses "." while my columns have "_"
# write the function to fix the names
fix_names <- function(x) gsub("\\.", "_", x)

#apply the function the effects and their confidence intervals
names(tot)   <- fix_names(names(tot))
names(dir)   <- fix_names(names(dir))
names(ind)   <- fix_names(names(ind))
colnames(tot.b) <- fix_names(colnames(tot.b))
colnames(dir.b) <- fix_names(colnames(dir.b))
colnames(ind.b) <- fix_names(colnames(ind.b))



#names(tot) <- gsub("\\.", "_", names(tot))
#colnames(tot.b) <- gsub("\\.", "_", colnames(tot.b))

#create a new dataframe called x that has the value of larval_treatment to predict clutch size for. it keeps pupal treatment constant at the mean, and keeps female mass constant at the mean.
x <- data.frame(
  numerical_larval_treatment = seq(min(sem_data$numerical_larval_treatment, na.rm = TRUE),
                                   max(sem_data$numerical_larval_treatment, na.rm = TRUE),
                                   length = 100),
  numerical_pupal_treatment  = mean(sem_data$numerical_pupal_treatment, na.rm = TRUE),
  weight_mg                  = mean(sem_data$weight_mg, na.rm = TRUE)
)

#use predEff()to predict the clutch size for our dataframe of larval treatment
fit_tot <- predEff(y_model, newdata = x, effects = tot, eff.boot = tot.b, type = "response")

fit_dir <- predEff(y_model, newdata = x, effects = dir, eff.boot = dir.b, type = "response")

fit_ind <- predEff(y_model, newdata = x, effects = ind, eff.boot = ind.b, type = "response")


```

```{r}
#now plot the effects
#write a function to plot the effects using ggplot2
plotFit <- function(x, fit, rawdata, xvar, yvar, x.lab = NULL, y.lab = NULL) {

  pred_df <- data.frame(
    x = x,
    fit = fit$fit,
    ci.l = fit$ci.lower,
    ci.u = fit$ci.upper
  )

  ggplot() +
    # raw data
    geom_point(data = rawdata,
               aes_string(x = xvar, y = yvar),
               alpha = 0.5) +

    # confidence ribbon
    geom_ribbon(data = pred_df,
                aes(x = x, ymin = ci.l, ymax = ci.u),
                fill = "blue", alpha = 0.15) +

    # fitted line
    geom_line(data = pred_df,
              aes(x = x, y = fit),
              color = "blue", linewidth = 1) +

    xlab(x.lab) +
    ylab(y.lab) +
    theme_bw()
}
```


```{r}
plotFit(
  x = x$numerical_larval_treatment,
  fit = fit_ind,
  rawdata = sem_data,
  xvar = "numerical_larval_treatment",
  yvar = "clutch_size",
  x.lab = "Larval treatment (total effect)",
  y.lab = "Clutch size"
)
```
now do this if i want to plot the direct, indirect and total effects all together in one plot

```{r}
#join the predicted total, direct, and indirect effect into one dataframe
df_plot <- rbind(
  data.frame(x = x$numerical_larval_treatment,
             fit = fit_tot$fit,
             ci.l = fit_tot$ci.lower,
             ci.u = fit_tot$ci.upper,
             effect = "Total"),

  data.frame(x = x$numerical_larval_treatment,
             fit = fit_dir$fit,
             ci.l = fit_dir$ci.lower,
             ci.u = fit_dir$ci.upper,
             effect = "Direct"),

  data.frame(x = x$numerical_larval_treatment,
             fit = fit_ind$fit,
             ci.l = fit_ind$ci.lower,
             ci.u = fit_ind$ci.upper,
             effect = "Indirect")
)
```


```{r}
#now plot all the effects together in one plot
ggplot() +
  # raw data
  #geom_point(data = sem_data,
          #aes(x = numerical_larval_treatment, y = clutch_size),
           # alpha = 0.8) +

  # confidence ribbons
  geom_ribbon(data = df_plot,
              aes(x = x, ymin = ci.l, ymax = ci.u, fill = effect),
              alpha = 0.2) +

  # lines
  geom_line(data = df_plot,
            aes(x = x, y = fit, colour = effect),
            linewidth = 1) +

  labs(
     x = expression("Resource acquisition temperature (" * degree * "C)"),
    y = "clutch size (number of eggs)",
    colour = "Effect",
    fill = "Effect"
  ) +
   geom_point(aes(x = 11.35602, y = 109),
             shape = 8, size = 4, colour = "black") +
    geom_point(aes(x = 12.523, y = 139),
             shape = 8, size = 4, colour = "black") +
  theme_bw() 
```

