---
title: "calculatin mean temp in each treatment"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(here)
library(car)
library(lubridate)
```

```{r}
ambient_temperatures <- read.csv(here("data", "clean data", "ambient temperatures.csv"))

incubator_treatments <- read.csv(here("data", "raw data", "mbiols_daily_temperature_data.csv"))

#to make sure dates are stored as dates, and temperatures as numbers
incubator_treatments <- incubator_treatments %>%
  mutate(
    date_1   = as.Date(date_1, format = "%d/%m/%Y"),
    date_end = as.Date(date_end, format = "%d/%m/%Y"),
    `plus2.5`    = as.numeric(`plus2.5`),
    `plus1.5`    = as.numeric(`plus1.5`),
    `actual.mean` = as.numeric(`actual.mean`),
    `minus1.5`   = as.numeric(`minus1.5`),
    `minus2.5`   = as.numeric(`minus2.5`)
  )
#combine date 1 and date end into one date column
incubator_treatments <- incubator_treatments %>%
  group_by(date_1, date_end, Hour_group) %>%
   pivot_longer(
    cols = c(date_1, date_end),
    names_to = "date_type",
    values_to = "date") %>%
  select(-date_type) 

#create datetime column
incubator_treatments <- incubator_treatments %>%
  mutate(datetime = as.POSIXct(paste(date, Hour_group),
                               format = "%Y-%m-%d %H",
                               tz = "UTC"))
#interpolate 2-hourly treatments into 1-hourly treatments
incubator_treatments_hourly <- incubator_treatments %>%
  ungroup() %>% 
  complete(datetime = seq(min(datetime, na.rm = TRUE),
                          max(datetime, na.rm = TRUE),
                          by = "1 hour")) %>%
  fill(everything(), .direction = "down")

#filter for the dates I want so the dataset doesn't get too big
incubator_treatments_hourly <- incubator_treatments_hourly %>%
  filter(datetime >= as.Date("2025-04-11") & datetime <= as.Date("2025-12-29"))

#interpolate to the minute increments that i want - so that it matches the ambient thermologger data.
offsets <- c(0, 10, 15, 20, 30, 40, 45, 50)

incubator_treatments_expanded <- incubator_treatments_hourly %>%
  uncount(length(offsets)) %>%
  group_by(datetime) %>%
  mutate(datetime = datetime + minutes(offsets[row_number()])) %>%
  ungroup()
```

RESOURCE ACQUISITION
```{r}
#dataset for period of resource alocation - using median pupation date and median emergence date
acquisition_ambient_temp <- ambient_temperatures %>%
  filter(datetime >= as.Date("2025-04-11") & datetime <= as.Date("2025-05-16"))

mean(acquisition_ambient_temp$temperature)
#12.36966

sd(acquisition_ambient_temp$temperature)
#4.394121


acquisition_incubator_temp <- incubator_treatments_expanded %>%
  filter(date >= as.Date("2025-04-11") & date <= as.Date("2025-05-16"))

mean(acquisition_incubator_temp$minus1.5)
#8.358796
sd(acquisition_incubator_temp$minus1.5)
#3.378171


mean(acquisition_incubator_temp$actual.mean)
#10.09398
sd(acquisition_incubator_temp$actual.mean)
#3.350202


mean(acquisition_incubator_temp$plus1.5)
#11.82685
sd(acquisition_incubator_temp$plus1.5)
#3.318277

mean(acquisition_incubator_temp$plus2.5)
#12.97963
sd(acquisition_incubator_temp$plus2.5)
#3.303401

```

RESOURCE ALLOCATION
```{r}
#dataset for period of resource acquisition - using median halfhatch date and median pupation date
allocation_ambient_temp <- ambient_temperatures %>%
  filter(datetime >= as.Date("2025-05-16") & datetime <= as.Date("2025-12-29"))

mean(allocation_ambient_temp$temperature)
#15.09694

sd(allocation_ambient_temp$temperature)
#5.544897


allocation_incubator_temp <- incubator_treatments_expanded %>%
  filter(date >= as.Date("2025-05-16") & date <= as.Date("2025-12-29"))

mean(allocation_incubator_temp$minus1.5)
#10.26442
sd(allocation_incubator_temp$minus1.5)
#5.541037


mean(allocation_incubator_temp$actual.mean)
#12.24573
sd(allocation_incubator_temp$actual.mean)
#5.359852


mean(allocation_incubator_temp$plus1.5)
#14.22307
sd(allocation_incubator_temp$plus1.5)
#5.191259

mean(allocation_incubator_temp$plus2.5)
#15.54408
sd(allocation_incubator_temp$plus2.5)
#5.082466

```

