---
title: "analysing ambient treatment"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(lme4)
```

```{r}
results <- read.csv(here("data", "clean data", "results.csv"), colClasses = c(sex = "character"))

results <- results %>%
  mutate(emergence_date = mdy(emergence_date)) %>%
  mutate(pupa_id = sub("_[^_]+$", "", adultID))

```

```{r}
pupation_data <- read.csv(here("data", "raw data", "pupation_data(Sheet1).csv"))

pupation_data <- pupation_data %>%
  select(pupa_id, date) %>%
  rename(pupation_date = date) %>%
  mutate(pupation_date = mdy(pupation_date))
         
```

```{r}
combined_data <- results %>%
  left_join(pupation_data, by = 'pupa_id' ) %>%
  select(adultID, pupa_id, pupal_treatment, larval_treatment, pupation_date, emergence_date) %>%
  filter()
```


```{r}
#Now just look at the pupation dates of those that were ambient as egg/larva
#then I want to calculate the mean/median pupation date of these, so I know what period of time to look at temperature.

ambient_larval_treatment <- combined_data %>%
  filter(larval_treatment == "ambient")


ggplot(ambient_larval_treatment, aes(x = pupation_date)) +
  geom_histogram(binwidth = 1) +
  labs(x = "Pupation Date", y = "Count", title = "pupation date of ambient larval treatment")

#calculate the median pupation date
median(ambient_larval_treatment$pupation_date, na.rm = TRUE)

#median pupation date for ambient treatment is "2025-05-16"

```

```{r}
#now look at the emergence date of those that were ambient as pupae

ambient_pupal_treatment <- combined_data %>%
  filter(pupal_treatment == "ambient"  & larval_treatment == "ambient")


ggplot(ambient_pupal_treatment, aes(x = emergence_date)) +
  geom_histogram(binwidth = 1) +
  labs(x = "Pupation Date", y = "Count", title = "emergence date of ambient larval treatment")

#calculate the median pupation date
median(ambient_pupal_treatment$emergence_date, na.rm = TRUE)

#the median pupation date of all larval treatments but ambient pupal treatment was "2025-12-01"
#the median pupation date of just ambient-ambient was "2025-11-29"
```


```{r}
#calculate the mean hatch date of eggs in ambient treatment, to calculate the period over which they were caterpillars

hatch_data <- read.csv(here("data", "raw data", "processed_cg_data.csv"))

#select only those that are ambient and are from wytham
hatch_data <- hatch_data %>%
  select(subclutch.id, halfdate) %>%
  filter(str_detect(subclutch.id, "CTRL\\.WTH"))

#calculate median halfhatch date
median_halfhatch_date  <- median(hatch_data$halfdate)
#the median julian halfhatch date of these clutches is 101.6496

#now convert from a julian date to an actual date
median_halfhatch_date <- as.Date(median_halfhatch_date - 1, origin = "2025-01-01")
#median halfhatch date is 2025-04-11 - the 11th April 2025
```

