---
title: "calculatin mean temp in each treatment"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(here)
library(car)
library(lubridate)
```

```{r}
ambient_temperatures <- read.csv(here("data", "clean data", "ambient temperatures.csv"))

ambient_temperatures$datetime <- parse_date_time(
  ambient_temperatures$datetime,
  orders = c("ymd HMS", "ymd"),
  tz = "UTC"
)


#filter the ambient temperatures for the whole period of resource acquisition and allocation
ambient_temperatures <- ambient_temperatures %>%
  filter(
    datetime >= as.POSIXct("2025-04-11 00:00:00", tz = "UTC"),
    datetime <= as.POSIXct("2025-12-29 23:50:00", tz = "UTC")
  )

#get the ambient temp at 2 hourly intervals like the incubator treatments
ambient_temp_2hourly <- ambient_temperatures %>%
  mutate(
    # round down the datetime to the previous even hour
    hour_bin = floor(hour(datetime) / 2) * 2,
    # define the bin ending at the *even hour*
    datetime = as.POSIXct(
      paste(as.Date(datetime), sprintf("%02d:00:00", hour_bin + 2)), 
      tz = "UTC"
    )
  ) %>%
  # only keep bins for even hours (optional; already ensured by +2)
  filter(hour_bin %% 2 == 0) %>%
  group_by(datetime) %>%
  summarise(mean_temperature = mean(temperature, na.rm = TRUE)) %>%
  ungroup()

#calculate the change int temperature from one timestep to the previous timestep
ambient_temp_2hourly <- ambient_temp_2hourly %>%
  arrange(datetime) %>%   # make sure it's in chronological order
  mutate(temp_change = mean_temperature - lag(mean_temperature))




incubator_treatments <- read.csv(here("data", "raw data", "mbiols_daily_temperature_data.csv"))

#to make sure dates are stored as dates, and temperatures as numbers
incubator_treatments <- incubator_treatments %>%
  mutate(
    date_1   = as.Date(date_1, format = "%d/%m/%Y"),
    date_end = as.Date(date_end, format = "%d/%m/%Y"),
    `plus2.5`    = as.numeric(`plus2.5`),
    `plus1.5`    = as.numeric(`plus1.5`),
    `actual.mean` = as.numeric(`actual.mean`),
    `minus1.5`   = as.numeric(`minus1.5`),
    `minus2.5`   = as.numeric(`minus2.5`)
  )

#combine date 1 and date end into one date column
incubator_treatments <- incubator_treatments %>%
  group_by(date_1, date_end, Hour_group) %>%
   pivot_longer(
    cols = c(date_1, date_end),
    names_to = "date_type",
    values_to = "date") %>%
  dplyr::select(-date_type) 

#create datetime column
incubator_treatments <- incubator_treatments %>%
  mutate(datetime = as.POSIXct(paste(date, Hour_group),
                               format = "%Y-%m-%d %H", tz = "UTC"))



cols_to_diff <- c("plus2.5", "plus1.5", "actual.mean", "minus1.5")

incubator_treatments <- incubator_treatments %>%
  arrange(datetime) %>%   # make sure data is in chronological order
  mutate(across(
    all_of(cols_to_diff),
    ~ . - lag(.),
    .names = "temp_change_{.col}"
  ))

```

RESOURCE ACQUISITION
```{r}
#dataset for period of resource alocation - using median pupation date and median emergence date
#acquisition_ambient_temp <- ambient_temperatures %>%
 # filter(datetime >= as.Date("2025-04-11") & datetime <= as.Date("2025-05-16"))

acquisition_ambient_temp <- ambient_temp_2hourly %>%
  filter(datetime >= as.POSIXct("2025-04-11 00:00:00") &
         datetime <= as.POSIXct("2025-05-16 23:59:59"))

mean(acquisition_ambient_temp$mean_temperature)
#12.38838

sd(acquisition_ambient_temp$mean_temperature)
#4.33


acquisition_incubator_temp <- incubator_treatments %>%
  filter(datetime >= as.POSIXct("2025-04-11 00:00:00") &
         datetime <= as.POSIXct("2025-05-16 23:59:59"))


# Convert wide to long so we have treatment and mean_temperature columns
plot_data_clean <- acquisition_incubator_temp %>%
  pivot_longer(
    cols = c(plus2.5, plus1.5, actual.mean, minus1.5),
    names_to = "treatment",
    values_to = "temperature") 
ggplot(plot_data_clean, aes(x = datetime, y = temperature, color = treatment)) +
  geom_line()


ggplot() +
    geom_line(data = plot_data_clean,
            aes(x = datetime, y = temperature, colour = treatment),
            alpha = 0.7,
            linewidth = 1.0) +
  scale_color_manual(
    values = c(
      "minus1.5" = "#76C0CC",
      "actual.mean"   = "#F9CA0F",
      "plus1.5"  = "#E87A36",
      "plus2.5"  = "#AF0808")) +
  geom_line(data = acquisition_ambient_temp,
            aes(x = datetime, y = temperature),
            colour = "black",
            linewidth = 1.0,
            alpha = 0.9) +

  labs(x = "Time",
       y = "Temperature",
       colour = "Treatment") +
  theme_bw()

mean(acquisition_incubator_temp$minus1.5)
#8.368837
sd(acquisition_incubator_temp$minus1.5)
#3.386495


mean(acquisition_incubator_temp$actual.mean)
#10.10372
sd(acquisition_incubator_temp$actual.mean)
#3.358597


mean(acquisition_incubator_temp$plus1.5)
#11.83628
sd(acquisition_incubator_temp$plus1.5)
#3.32678

mean(acquisition_incubator_temp$plus2.5)
#12.98884
sd(acquisition_incubator_temp$plus2.5)
#3.311922

```

RESOURCE ALLOCATION
```{r}
#dataset for period of resource acquisition - using median halfhatch date and median pupation date

allocation_ambient_temp <- ambient_temp_2hourly %>%
  filter(datetime >= as.POSIXct("2025-05-16 00:00:00") &
         datetime <= as.POSIXct("2025-12-29 23:59:59"))

ggplot(allocation_ambient_temp, aes(x = datetime, y = temperature)) +
  geom_line()


mean(allocation_ambient_temp$mean_temperature)
#14.34711

sd(allocation_ambient_temp$mean_temperature)
#5.842382


allocation_incubator_temp <- incubator_treatments %>%
  filter(datetime >= as.POSIXct("2025-05-16 00:00:00") &
         datetime <= as.POSIXct("2025-12-29 23:59:59"))


# Convert wide to long so we have treatment and mean_temperature columns
plot_data_clean <- allocation_incubator_temp %>%
  pivot_longer(
    cols = c(plus2.5, plus1.5, actual.mean, minus1.5),
    names_to = "treatment",
    values_to = "temperature") 
ggplot(plot_data_clean, aes(x = datetime, y = temperature, color = treatment)) +
  geom_line()


ggplot() +
  geom_line(data = plot_data_clean,
            aes(x = datetime, y = temperature, colour = treatment),
            alpha = 0.5,
            linewidth = 0.1) +
  scale_color_manual(
    values = c(
      "minus1.5" = "#76C0CC",
      "actual.mean"   = "#F9CA0F",
      "plus1.5"  = "#E87A36",
      "plus2.5"  = "#AF0808")) +
  geom_line(data = allocation_ambient_temp,
            aes(x = datetime, y = temperature),
            colour = "#484A4C",
            linewidth = 0.1) +
  labs(x = "Time",
       y = "Temperature",
       colour = "Treatment") +
  theme_bw()

mean(allocation_incubator_temp$minus1.5)
#10.22277
sd(allocation_incubator_temp$minus1.5)
#5.568563


mean(allocation_incubator_temp$actual.mean)
#12.20691
sd(allocation_incubator_temp$actual.mean)
#5.384005


mean(allocation_incubator_temp$plus1.5)
#14.18713
sd(allocation_incubator_temp$plus1.5)
#5.211962

mean(allocation_incubator_temp$plus2.5)
#15.51012
sd(allocation_incubator_temp$plus2.5)
#5.100805

```

