---
title: "modelling caterpillars"
output: html_document
---
```{r}
library(lme4)
library(lmerTest)
library(performance)
```


```{r}
#model whether hatching or not is explained by egg size and pupal treatment, with clutch ID as a random effect
#caterpillar ID can't be included as a random effect nested in clutchID becuase it complains that the model is singular

caterpillar_data <- read.csv(here("data", "clean data", "caterpillar_data.csv"))


caterpillar_data$hatch_date <- as.Date(caterpillar_data$hatch_date)
caterpillar_data$weighday_1 <- as.Date(caterpillar_data$weighday_1)
caterpillar_data$weighday_2 <- as.Date(caterpillar_data$weighday_2)
caterpillar_data$weighday_3 <- as.Date(caterpillar_data$weighday_3)
caterpillar_data$weighday_4 <- as.Date(caterpillar_data$weighday_4)


#distribution of hatch dates
ggplot(caterpillar_data, aes(x = hatch_date)) +
  geom_histogram(binwidth = 1) +
  scale_x_date(date_labels = "%b %d", date_breaks = "2 days") +
  labs(x = "Hatch Date", y = "Count")

#to count how many eggs hatched
#caterpillar_data <- caterpillar_data %>%
  #filter(hatched == 1)
#181 hatched so far


caterpillar_data$clutchID <- as.factor(caterpillar_data$clutchID)

model <- glmer(hatched ~ size_01 + pupal_treatment + (1 | clutchID), data = caterpillar_data, family = binomial)

summary(model)
#neither egg size nor pupal treatment explain hatching success

icc(model)
#use adjusted ICC
#around 29% of variation in hatching success is explained by clutchID



#model assumptions test 
library(DHARMa)

sim_res <- simulateResiduals(model)
plot(sim_res)


#now I want to model whether weight is explained by size, pupal_treatment, julian hatch date, and clutchID as a random effect

```



