---
title: "modelling 2.0"
output: html_document
---


```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(lme4)
library(emmeans)
library(lmerTest)
library(ggeffects)
```
working on the raw egg size measurements for each individual egg

AMBIENT, WARM AND HOT LARVAL TEMPERATURE
```{r}
raw_egg_sizes <- read.csv(here("data", "clean data", "raw egg sizes.csv"))

mean(raw_egg_sizes$area)
sd(raw_egg_sizes$area)

raw_egg_sizes %>%
  filter(pupal_treatment == "wild") %>%
  group_by(pupal_treatment) %>%
  summarise(mean_egg_size = mean(area), n = n())


raw_egg_sizes <- raw_egg_sizes %>%
  mutate(grandmotherID = sub("^[^.]*\\.[^.]*\\.([^_]+)_.*$", "\\1", adultID))

#remove this adultID because it doens't have a grandmotherID
raw_egg_sizes <- raw_egg_sizes %>%
  filter(adultID != "CTRL.WTH_P8_W")

#make maternal ID a factor
raw_egg_sizes$grandmotherID <- as.factor(raw_egg_sizes$grandmotherID)

#make clutchID a factor
raw_egg_sizes$motherID <- as.factor(raw_egg_sizes$clutchID)

#convert the pupal temperatures to factors so they plot in the correct order
raw_egg_sizes$pupal_treatment <- factor(raw_egg_sizes$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#convert the larval  temperatures to factors so the plot in the correct order
raw_egg_sizes$larval_treatment <- factor(raw_egg_sizes$larval_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#mean and SD of all egg sizes
summary(raw_egg_sizes$egg_mean_1A)
sd(raw_egg_sizes$egg_mean_1A)


#looking just at ambient, warm and hot larval temperature - need to remove wild because they don't have weight, or maternal ID or clutchID
egg_sizes_filtered <- raw_egg_sizes %>%
  filter(larval_treatment %in% c("ambient", "warm", "hot")) %>%
  mutate(weight_mg = weight * 1000) %>%
  mutate(weight_mg_centered = weight_mg - mean(weight_mg, na.rm = TRUE))



egg_sizes_filtered %>%
  group_by(pupal_treatment) %>%
  summarise(mean_egg_size = mean(area), n = n())



```

```{r}
#look at the distributions of egg size
ggplot(egg_sizes_filtered, aes(x = area)) +
  geom_histogram(binwidth = 0.01) +  # change this value to control bin width +
  labs(title = "Distribution of Egg Sizes",
       x = "Egg Area",
       y = "Count") +
  theme_minimal()
```


```{r}



lm4 <- lmer(area ~ larval_treatment * pupal_treatment + (1|grandmotherID/motherID) + weight_mg_centered, data = egg_sizes_filtered)
summary(lm4)

anova(lm4)


tab_model(lm4,
          transform = NULL,   
          show.se = TRUE,   
          show.ci = FALSE) 

#test the effect of the interaction term 
lm4_no_interaction <- lmer(area ~ larval_treatment + pupal_treatment + (1|grandmotherID/motherID) + weight_mg_centered, data = egg_sizes_filtered)
anova(lm4, lm4_no_interaction)
#interaction effect not significant


#test the overall effect of pupal temperature
lm4_no_pupal <- lmer(area ~ larval_treatment + (1|grandmotherID/motherID) + weight_mg_centered, data = egg_sizes_filtered)
anova(lm4_no_interaction, lm4_no_pupal)
#pupal effect very significant

#test the overall effect of larval temperature
lm4_no_larval <- lmer(area ~ pupal_treatment + (1|grandmotherID/motherID) + weight_mg_centered, data = egg_sizes_filtered)
anova(lm4_no_interaction, lm4_no_larval)
#larval temp is significant overall

confint(lm4)
#confidence intervals of larval treatment effects overlap with zero
```

```{r}
#pairwise comparisons
#estimates marginal means for the pupal treatments
emm <- emmeans(lm4_no_interaction, ~ pupal_treatment)
emm
pairs(emm)
summary(emm)
#significant difference between ambient-mean, ambient-warm, and ambient-hot.


#estimate marginal means based on larval treatment
emm <- emmeans(lm4_no_interaction, ~ larval_treatment)
emm
pairs(emm)



pred <- ggeffects::ggpredict(lm4_no_interaction,
                  terms = c("pupal_treatment"))

#assign colours to the temperatures                           
temp_cols <- c(
  ambient = "#484A4C",
  cool    = "#76C0CC",
  mean    = "#F9CA0F",
  warm    = "#E87A36",
  hot     = "#AF0808")

ggplot(pred, aes(x = x, y = predicted)) +
  geom_point(color = temp_cols) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
                width = 0.1) +
  #scale_y_continuous(limits = c(0.190, 0.215)) +
  #scale_color_manual(values = temp_cols) +
  labs(
    x = "Resource allocation treatment",
    y = expression(Predicted~egg~area~(mm^2))
  ) +
  theme_bw()

egg_size_model <- ggplot(pred, aes(x = x, y = predicted)) +
  # raw data
  #geom_jitter(data = egg_sizes_filtered,
            #  aes(x = pupal_treatment, y = area),
            #  width = 0.15,
            #  alpha = 0.4,
            #  color = "grey") +
  scale_y_continuous(breaks = seq(0.20, 0.21, by = 0.01)) +
  
  # model predictions
  geom_point(color = temp_cols, size = 6) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
                width = 0.1) +
  
  labs(
    x = "Resource allocation temperature",
    y = expression(Individual~egg~area~(mm^2)),
    title = "B) Model estimates for individual egg size"
  ) +
  theme_bw() +
    theme(
    text = element_text(size = 18),            # increases all text
    axis.title = element_text(size = 20),      # axis titles bigger
    axis.text = element_text(size = 18),       # axis tick labels bigger
    legend.text = element_text(size = 18),     # legend text bigger
    legend.title = element_text(size = 20)
    )

egg_size_model


```
AMBIENT AND WILD COMPARISON
```{r}
ambient_and_wild <- raw_egg_sizes %>%
  filter(pupal_treatment %in% c("wild", "ambient")) %>%
   mutate(
    larval_treatment = factor(larval_treatment, levels = c("ambient", "wild")))

lm1 <- lm(area ~ larval_treatment, data = ambient_and_wild)
summary(lm1)

tab_model(lm1,
          transform = NULL,   
          show.se = TRUE,   
          show.ci = FALSE)
```





