---
title: "modelling trade-off"
output: html_document
---

```{r}
library(lme4)
library(purrr)
library(broom)
library(MASS)
library(here)
library(dplyr)
```

WARM AND HOT LARVAL TEMP
```{r}
results <- read.csv(here("data", "clean data", "results.csv"), colClasses = c(sex = "character"))

#make maternal ID a factor
results$maternalID <- as.factor(results$maternalID)

#make a treatment combination column
results <- results %>%
  mutate(treatment_combination = paste(larval_treatment, pupal_treatment, sep = "_"))  %>%
  filter(larval_treatment %in% c("warm", "hot")) %>%
  mutate(
    larval_treatment = factor(larval_treatment, levels = c("warm","hot")),
    pupal_treatment = factor(pupal_treatment, levels = c("ambient", "cool","mean","warm","hot"))
  ) %>%
    mutate(weight_mg = weight * 1000)  %>%
  mutate(weight_mg_centered = weight_mg - mean(weight_mg, na.rm = TRUE))

 
```

```{r}
lm1 <- lm(egg_mean_1A ~ clutch_size, data = results)
summary(lm1)
AIC(lm1)
#AIC = -1169

lm2 <- lm(egg_mean_1A ~ clutch_size + larval_treatment, data = results)
summary(lm2)
AIC(lm2)
#AIC = -1167

lm3 <- lm(egg_mean_1A ~ clutch_size + pupal_treatment, data = results)
summary(lm3)
AIC(lm3)
#AIC = -1171

lm4 <- lm(egg_mean_1A ~ clutch_size + pupal_treatment + larval_treatment, data = results)
summary(lm4)
AIC(lm4)
#AIC = -1169

lm5 <- lmer(egg_mean_1A ~ clutch_size + pupal_treatment + larval_treatment + (1|maternalID), data = results)
summary(lm5)
AIC(lm5)
#AIC = -1105

lm6 <- lm(egg_mean_1A ~ clutch_size + pupal_treatment + weight_mg_centered, data = results)
summary(lm6)
AIC(lm6)
#AIC = -1169
#female mass does not have an effect on egg size




```

```{r}
warm_cool <-
  results %>%
  filter(treatment_combination == "warm_cool")

lm1 <- lm(egg_mean_1A ~ clutch_size, data = warm_cool)
summary(lm1)
AIC(lm1)


warm_mean <-
  results %>%
  filter(treatment_combination == "warm_mean")

lm2 <- lm(egg_mean_1A ~ clutch_size, data = warm_mean)
summary(lm2)
AIC(lm2)


warm_warm <-
  results %>%
  filter(treatment_combination == "warm_warm")

lm3 <- lm(egg_mean_1A ~ clutch_size, data = warm_warm)
summary(lm3)
AIC(lm3)


warm_hot <-
  results %>%
  filter(treatment_combination == "warm_hot")

lm4 <- lm(egg_mean_1A ~ clutch_size, data = warm_hot)
summary(lm4)
AIC(lm4)
```

Wild moths

```{r}
results <- read.csv(here("data", "clean data", "results.csv"), colClasses = c(sex = "character"))

results_wild <- results %>%
  filter(pupal_treatment == "wild")

lm1 <- lm(egg_mean_1A ~ clutch_size, data = results_wild)
summary(lm1)


```
ambient larval temp 

```{r}
results <- read.csv(here("data", "clean data", "results.csv"), colClasses = c(sex = "character"))

results_ambient <- results %>%
  filter(larval_treatment == "ambient")

lm1 <- lm(egg_mean_1A ~ clutch_size, data = results_ambient)
summary(lm1)
AIC(lm1)

#best model
lm2 <- lm(egg_mean_1A ~ clutch_size + pupal_treatment, data = results_ambient)
summary(lm2)
AIC(lm2)

lm3 <- lm(egg_mean_1A ~ clutch_size * pupal_treatment, data = results_ambient)
summary(lm3)
AIC(lm3)
```

