---
title: "modelling clutch size"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(lme4)
library(performance)
library(MASS)
library(pscl)
library(piecewiseSEM)
library(semPlot)
```

```{r}

results <- read.csv(here("data", "clean data", "results.csv"), colClasses = c(sex = "character"))

#make maternal ID a factor
results$maternalID <- as.factor(results$maternalID)

#make a treatment combination column
results <- results %>%
  mutate(treatment_combination = paste(larval_treatment, pupal_treatment, sep = "_"))  %>%
  mutate()

#number of mated females in each treatment group 
table(results$treatment_combination)

#remove ambient, because these need to be modelled separately. also remove larval treatment of cool and mean, because the sample size isn't big enough to model - just not enough clutches.
#I think I will model the ambient larva treatment separately.
results_filtered <- results %>%
  filter(pupal_treatment != "ambient",
         larval_treatment != "ambient",
         larval_treatment != "cool",
        larval_treatment != "mean",
         larval_treatment != "wild") %>%
  mutate(numerical_pupal_treatment = case_when(
    pupal_treatment == "cool"  ~ -1.5,
    pupal_treatment == "mean"  ~  0.0,
    pupal_treatment == "warm"  ~  1.5,
    pupal_treatment == "hot"   ~  2.5,
    TRUE ~ NA_real_
  )) %>% 
  mutate(numerical_larval_treatment = case_when(
    larval_treatment == "warm"  ~  1.5,
    larval_treatment == "hot"   ~  2.5,
    TRUE ~ NA_real_
  )) %>%
  mutate(weight_mg = weight * 1000) %>%
  mutate(weight_mg_centered = weight_mg - mean(weight_mg, na.rm = TRUE))


results_filtered <- results_filtered %>%
  mutate(
    larval_treatment = factor(larval_treatment, levels = c("warm","hot")),
    pupal_treatment = factor(pupal_treatment, levels = c("cool","mean","warm","hot"))
  )

#how many eggs were counted in total
sum(results$clutch_size) 


```

```{r}
#look at the distribution of clutch size
ggplot(results, aes(x = clutch_size)) +
  geom_histogram(binwidth = 5) +  # change this value to control bin width +
  labs(title = "Distribution of clutch size",
       x = "clutch size",
       y = "Count") +
  theme_minimal()

# mean
mean(results_filtered$clutch_size, na.rm = TRUE)

# variance
var(results_filtered$clutch_size, na.rm = TRUE)

#the mean is much greater than the variance, suggesting that a negative binomial model might be better than the poisson model


pois_mod <- glm(clutch_size ~ 1, family = poisson(link = "log"), data = results)

nb_mod <- glm.nb(clutch_size ~ 1, data = results)

AIC(pois_mod, nb_mod)
#the AIC is way, way lower for the negative binomial model, so this is the better model to use.






#look at the distribution of female mass
ggplot(results, aes(x = weight)) +
  geom_histogram(binwidth = 0.005) +  # change this value to control bin width +
  labs(title = "Distribution of female mass",
       x = "female mass",
       y = "Count") +
  theme_minimal()

#look at the distribution of mean egg sizes
ggplot(results, aes(x = egg_mean_1A)) +
  geom_histogram(binwidth = 0.01) +  # change this value to control bin width +
  labs(title = "Distribution of mean egg size",
       x = "mean egg size",
       y = "Count") +
  theme_minimal()
```



```{r}
#trying negative binomial models
lm1_nb <- glm.nb(clutch_size ~  larval_treatment, data = results_filtered)
summary(lm1_nb)
AIC(lm1_nb)

lm2_nb <- glm.nb(clutch_size ~  larval_treatment + weight_mg_centered, data = results_filtered)
summary(lm2_nb)
AIC(lm2_nb)

lm3_nb <- glm.nb(clutch_size ~  larval_treatment + pupal_treatment + weight_mg_centered, data = results_filtered)
summary(lm3_nb)
AIC(lm3_nb)

lm4_nb <- glmer.nb(clutch_size ~  larval_treatment + pupal_treatment + weight_mg_centered + (1|maternalID), data = results_filtered)
summary(lm4_nb)
```



```{r}
#now try zero-inflated negative binomial models 
lm1_zinb <- zeroinfl(clutch_size ~  larval_treatment, data = results_filtered, dist = "negbin")
summary(lm1_zinb)
AIC(lm1_zinb)

lm2_zinb <- zeroinfl(clutch_size ~  larval_treatment + weight_mg_centered, data = results_filtered, dist = "negbin")
summary(lm2_zinb)
AIC(lm2_zinb)

lm3_zinb <- zeroinfl(clutch_size ~  larval_treatment + pupal_treatment + weight_mg_centered, data = results_filtered, dist = "negbin")
summary(lm3_zinb)
```




```{r}
#hurdle models
mod.hurdl_1 <- hurdle(clutch_size ~ larval_treatment, data = results_filtered, dist = "negbin")
summary(mod.hurdl_1)
AIC(mod.hurdl_1)

mod.hurdl_2 <- hurdle(clutch_size ~ larval_treatment + weight_mg_centered, data = results_filtered, dist = "negbin")
summary(mod.hurdl_2)
AIC(mod.hurdl_2)

mod.hurdl_3 <- hurdle(clutch_size ~ larval_treatment + pupal_treatment + weight_mg_centered, data = results_filtered, dist = "negbin")
summary(mod.hurdl_3)
AIC(mod.hurdl_3)


```

```{r}
#library(lavaan)

path_model <- "
  clutch_size ~ numerical_larval_treatment
  clutch_size ~ a*weight_mg
  weight_mg ~ b*numerical_larval_treatment
  indirect:=a*b
"

path_estimate <- sem(path_model, data = results_filtered, se = "bootstrap")

summary(path_estimate, ci = TRUE)
#ok this comes out with significant indirect effects but it doesn't use the negative binomial distribution, which is important when I have zeros and overdispersed count data
#another option is piecewise SEM with negative binomial distribution

AIC(path_estimate)


library(semPlot)

semPaths(path_estimate,
         what = "std",          # standardized estimates
         layout = "tree",
         edge.label.cex = 1.2,
         sizeMan = 8,
         nCharNodes = 0,
         residuals = FALSE)
```

```{r}
#try piecewise SEM
#library(piecewiseSEM) 

#remove zeros from the dataset because I can't do a ZINB or a hurdle model in PSEM
results_filtered <- results_filtered %>%
 filter(clutch_size != 0) %>%
  filter(!is.na(egg_mean_1A)) %>%
  mutate(numerical_larval_treatment = case_when(
    larval_treatment == "warm"  ~  1.5, #recode the numerical larval treatments
    larval_treatment == "hot"   ~  2.5))


m_model <- lm(weight_mg ~ numerical_larval_treatment, data = results_filtered)

y_model <- glm.nb(clutch_size ~ numerical_larval_treatment + weight_mg,  data = results_filtered)



sem_model <- psem(m_model, y_model)



summary(sem_model, standardize = "scale", direction = c("weight_mg _> clutch_size"))

plot(sem_model, show = "std", digits = 2)

 
```








```{r}
m_model <- lm(weight_mg ~ numerical_larval_treatment + numerical_pupal_treatment, data = results_filtered)

y_model <- glm.nb(clutch_size ~ numerical_larval_treatment + numerical_pupal_treatment + weight_mg,  data = results_filtered)

x_model <- lmer(egg_mean_1A ~ numerical_pupal_treatment + numerical_larval_treatment + weight_mg + clutch_size + (1|maternalID), data = results_filtered)

sem_model <- psem(m_model, y_model, x_model)



summary(sem_model, standardize = "scale")

plot(sem_model, show = "std", digits = 2)
```




```{r}

# Models
m_model <- lm(weight_mg ~ numerical_larval_treatment + numerical_pupal_treatment,
              data = results_filtered)

y_model <- glm.nb(clutch_size ~ numerical_larval_treatment + numerical_pupal_treatment + weight_mg,
                  data = results_filtered)

x_model <- lmer(egg_mean_1A ~ numerical_pupal_treatment + numerical_larval_treatment + weight_mg + clutch_size +
                  (1|maternalID), data = results_filtered)

# SEM with correlated error between clutch size and egg size
sem_model <- psem(
  m_model,
  y_model,
  x_model,
  clutch_size %~~% egg_mean_1A   # this adds the correlated residual
)

# Summary with standardized coefficients
summary(sem_model, standardize = "scale", conserve = TRUE)

# Plot standardized SEM
plot(sem_model, show = "std", digits = 2)
```


```{r}
#looking at the effect of larval treatment on female mass
results <- results %>%
  mutate(
    larval_treatment = factor(larval_treatment, levels = c("cool","mean","warm","hot"))
  ) %>%
  mutate(weight_mg = weight * 1000)



wm_1 <- lm(weight_mg ~ larval_treatment, data = results)
summary(wm_1)

AIC(wm_1)
```





























THOSE THAT HAD AMBIENT LARVAL TREATMENT
```{r}
#going to try modelling those that had ambient larval temp

results <- read.csv(here("data", "clean data", "results.csv"), colClasses = c(sex = "character"))

#make maternal ID a factor
results$maternalID <- as.factor(results$maternalID)

#make a treatment combination column
results <- results %>%
  mutate(treatment_combination = paste(larval_treatment, pupal_treatment, sep = "_"))  %>%
  mutate()


#remove ambient, because these need to be modelled separately. also remove larval treatment of cool and mean, because the sample size isn't big enough to model - just not enough clutches.
#I think I will model the ambient larva treatment separately.
results_ambient_larval <- results %>%
  mutate(numerical_pupal_treatment = case_when(
    pupal_treatment == "cool"  ~ -1.5,
    pupal_treatment == "mean"  ~  0.0,
    pupal_treatment == "warm"  ~  1.5,
    pupal_treatment == "hot"   ~  2.5,
    TRUE ~ NA_real_ )) %>%
    filter(
         larval_treatment == "ambient",
         pupal_treatment != "ambient") %>%
  mutate(weight_mg = weight * 1000) %>%
  mutate(weight_mg_centered = weight_mg - mean(weight_mg, na.rm = TRUE))


results_ambient_larval <- results_filtered %>%
  mutate(
    pupal_treatment = factor(pupal_treatment, levels = c("cool","mean","warm","hot"))
  )

results_filtered$numerical_pupal_treatment2 <- results_filtered$numerical_pupal_treatment^2

```



```{r}
lm1_nb <- glm.nb( clutch_size ~ numerical_pupal_treatment + numerical_pupal_treatment2, data = results_filtered)

summary(lm1_nb)
```






