---
title: "modelling growth rate"
output: html_document
---

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(patchwork)
library(purrr)
library(broom)
library(nlme)
library(lme4)
```

```{r}
caterpillar_data <- read.csv(here("data", "clean data", "caterpillar_data.csv"))

#caterpillar_data <- caterpillar_data %>%
  #filter(!is.na(hatch_date)) 

caterpillar_data$pupal_treatment <- as.factor(caterpillar_data$pupal_treatment)
caterpillar_data$hatch_date <- as.Date(caterpillar_data$hatch_date)
caterpillar_data$weight_1 <- as.numeric(caterpillar_data$weight_1)
caterpillar_data$weight_2 <- as.numeric(caterpillar_data$weight_2)

#turn all weights into mg
caterpillar_data$weight_1 <- caterpillar_data$weight_1 * 1000
caterpillar_data$weight_2 <- caterpillar_data$weight_2 * 1000
caterpillar_data$weight3 <- caterpillar_data$weight3 * 1000
caterpillar_data$weight4 <- caterpillar_data$weight4 * 1000
caterpillar_data$weight_5 <- caterpillar_data$weight_5 * 1000

#remove rows where hatched is NA, and where there are not at least two weights
caterpillar_data <- caterpillar_data %>%
  filter(!is.na(hatched)) %>%
  filter(!is.na(weight_2))

```

```{r}
#fix the names of the columns
names(caterpillar_data) <- names(caterpillar_data) %>%
  gsub("^weight([0-9]+)$", "weight_\\1", .)

#turn the data into long format
long_data <- caterpillar_data %>%
  mutate(id = row_number()) %>%
  pivot_longer(
    cols = matches("^(weight|weighday)_\\d+$"),
    names_to = c(".value", "time"),
    names_pattern = "(weight|weighday)_(\\d+)"
  )

#save weighday as a date
long_data$weighday <- as.Date(long_data$weighday)

#add a days post hatch column
long_data <- long_data %>%
  mutate(days_post_hatch = as.numeric(weighday - hatch_date)) %>%
  filter(!is.na("weight"))
```

```{r}
#remove rows with NAs
long_data <- long_data %>%
  dplyr::filter(
    !is.na(weight),
    !is.na(days_post_hatch),
    !is.na(eggID)
  )

#group the data by eggID, and then for each eggID estimate the best-fitting line. then extract the coefficient of that line (the slope). This is the growth rate of the caterpillar as mg per day/
slopes <- long_data %>%
  group_by(eggID) %>%
  summarise(
    slope = coef(lm(weight ~ days_post_hatch))[2]
  )



#random intercepts and random slopes for each egg
#model <- lmer(weight ~  days_post_hatch + (days_post_hatch | eggID), data = long_data)
#summary(model)
#coef(model)$eggID
#at the moment this model is singular but hopefully that will be resolved once I have more data??

#extract the slope (the gradient) of the line for each egg
#slopes_df <- data.frame(
 # eggID = rownames(coef(model)$eggID),
#  slope = coef(model)$eggID[, "days_post_hatch"]
#)

#now i want to join this back onto the caterpillar_data spreadsheet
caterpillar_data <- caterpillar_data %>%
  left_join(slopes, by = "eggID")

#plot the relationship between growth rate and egg size
ggplot(caterpillar_data, aes(x = size_01, y = slope)) +
  geom_point(size = 3) +
labs( x = "egg size", y = "growth rate (mg/day)")

#now make a model of growth rate and size
model <- lmer(slope ~ size_01 + pupal_treatment + (1|clutchID), data = caterpillar_data)
summary(model)
AIC(model)

```





```{r}
#random intercepts and random slopes
model <- lmer(weight ~ days_post_hatch * size_01 + pupal_treatment + (1 | clutchID) + (days_post_hatch | eggID), data = long_data)

summary(model)

#random intercepts only
model <- lmer(weight ~ days_post_hatch * size_01 + pupal_treatment + (1 | clutchID/eggID), data = long_data)
summary(model)


model <- lmer(weight ~ days_post_hatch * size_01 + days_post_hatch * pupal_treatment + (1|clutchID/eggID), data = long_data)

summary(model)

plot(model)
```

