---
title: "adult mass"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(patchwork)
```


```{r}
#read in the results data
results <- read.csv(here("data", "clean data", "results.csv"))


#convert the pupal temperatures to factors so they plot in the correct order
results$pupal_treatment <- factor(results$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#convert the larval  temperatures to factors so the plot in the correct order
results$larval_treatment <- factor(results$larval_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))



```

```{r}
weight_results <- results %>%
   filter(pupal_treatment != "wild")

#convert the pupal temperatures to factors so they plot in the correct order
weight_results$pupal_treatment <- factor(weight_results$pupal_treatment,
                             levels = c("ambient", "cool", "mean", "warm", "hot"))

#convert the larval  temperatures to factors so the plot in the correct order
weight_results$larval_treatment <- factor(weight_results$larval_treatment,
                             levels = c("ambient", "cool", "mean", "warm", "hot"))

```

```{r}

#assign colours to the temperatures                           
temp_cols <- c(
  ambient = "#484A4C",
  cool    = "#76C0CC",
  mean    = "#F9CA0F",
  warm    = "#E87A36",
  hot     = "#AF0808")


```


```{r}
larval_levels <- c( "ambient", "cool", "mean", "warm", "hot")

plots <- lapply(larval_levels, function(lt) {

  ggplot(
    weight_results %>% 
    filter(larval_treatment == lt),
    aes(x = pupal_treatment, y = weight, fill = pupal_treatment)
  ) +
    geom_jitter(aes(color = pupal_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    scale_x_discrete(
        limits = levels(weight_results$pupal_treatment),
        drop = FALSE) +
    scale_y_continuous(limits = c(0.006, 0.05)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(
      x = "Pupal temperature",
      y = "female mass (g)",
      title = paste("Larval temperature:", lt)
    )
})


adult_mass_plot <- wrap_plots(plots, ncol = 3)

ggsave(
  here("figures", "adult mass and clutch size.png"),
  plot = adult_mass_plot,
  width = 17,
  height = 10,
  dpi = 300
)

# View first plot
plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]
plots[[5]]
```

```{r}
ggplot(weight_results,
    aes(x = larval_treatment, y = weight, fill = larval_treatment)) +
    geom_jitter(aes(color = larval_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    scale_x_discrete(
        limits = levels(weight_results$pupal_treatment),
        drop = FALSE) +
    scale_y_continuous(limits = c(0.006, 0.05)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
  geom_vline(xintercept = 1.5, linetype = "dashed", color = "black") +
    theme_bw() +
    theme(legend.position = "none") +
    labs(
      x = "larval temperature",
      y = "female mass (g)",
      title = paste("")
    )
```





```{r}
ggplot(weight_results, aes(x = weight, y = clutch_size, fill = larval_treatment)) +
  geom_point(aes(color = larval_treatment)) +
  scale_color_manual(values = temp_cols) +
  theme_bw() +
    labs(
      x = "female mass (g)",
      y = "clutch size (number of eggs)")


ggplot(weight_results, aes(x = weight, y = egg_mean_1A)) +
  geom_point() +
    labs(
      x = "female mass",
      y = "egg size")

weight_and_clutch_size <- ggplot(weight_results, aes(x = weight, y = egg_mean_1A)) +
  geom_point() +
  facet_wrap(~ pupal_treatment + larval_treatment) +
    labs(
      x = "female mass",
      y = "egg size")



ggsave(
  here("figures", "weight and clutch size.png"),
  plot = weight_and_clutch_size,
  width = 17,
  height = 10,
  dpi = 300
)



```

