---
title: "clutch size"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(patchwork)
library(ggdist)
```


```{r}
#read in the results data
results <- read.csv(here("data", "clean data", "results.csv"))


#convert the pupal temperatures to factors so they plot in the correct order
results$pupal_treatment <- factor(results$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#convert the larval  temperatures to factors so the plot in the correct order
results$larval_treatment <- factor(results$larval_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#assign colours to the temperatures                           
temp_cols <- c(
  ambient = "#484A4C",
  cool    = "#76C0CC",
  mean    = "#F9CA0F",
  warm    = "#E87A36",
  hot     = "#AF0808")

#remove clutches of 0 eggs
results <- results %>%
  filter(clutch_size != 0)

```

TOTAL CLUTCH SIZE

```{r}
larval_temp_ambient <- ggplot(
  results %>% filter(larval_treatment == "ambient"),
  aes(x = pupal_treatment, y = clutch_size, fill = pupal_treatment)
) +
  geom_jitter(aes(color = pupal_treatment),
              width = 0.15, size = 2, alpha = 0.8) +
  geom_boxplot(alpha = 0.5, width = 0.7) +
   geom_vline(xintercept = 2.5, linetype = "dashed", color = "black") +
  coord_cartesian(ylim = c(0, 400)) +
  scale_x_discrete(
    limits = levels(results$pupal_treatment),
    drop = FALSE
  ) +
  scale_fill_manual(values = temp_cols) +
  scale_color_manual(values = temp_cols) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    x = "Pupal temperature",
    y = "Clutch size (number of eggs)",
    title = "Larval temperature: ambient OR wild") +
  #overlay wild data
  geom_jitter(
    data = results %>% 
      filter(larval_treatment == "wild"),
    aes(x = pupal_treatment, y = clutch_size),
    inherit.aes = FALSE,
    color = "#D0CDCE",
    width = 0.15,
    size = 2,
    alpha = 0.8) +
  geom_boxplot(
    data = results %>% filter(larval_treatment == "wild"),
    aes(x = pupal_treatment, y = clutch_size),
    inherit.aes = FALSE,
    fill = "#D0CDCE",
    alpha = 0.3,
    width = 0.7,
    outlier.shape= NA
  )

larval_temp_ambient



```


```{r}

larval_levels <- c("cool", "mean", "warm", "hot")

plots <- lapply(larval_levels, function(lt) {

  ggplot(
    results %>% 
    filter(larval_treatment == lt),
    aes(x = pupal_treatment, y = clutch_size, fill = pupal_treatment)) +
    geom_jitter(aes(color = pupal_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape= NA) +
    geom_vline(xintercept = 2.5, linetype = "dashed", color = "black") +
    scale_x_discrete(
        limits = levels(results$pupal_treatment),
        drop = FALSE) +
     coord_cartesian(ylim = c(0, 400)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(
      x = "Pupal temperature",
      y = "Clutch size (number of eggs)",
      title = paste("Larval temperature:", lt)
    )
})

all_plots <- c(list(larval_temp_ambient), plots)

clutch_size_and_temp <- wrap_plots(all_plots, ncol = 3)

ggsave(
  here("figures", "clutch size and temp.png"),
  plot = clutch_size_and_temp,
  width = 20,
  height = 10,
  dpi = 300
)



# View first plot
plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]




```
```{r}

ggplot(results,
    aes(x = larval_treatment, y = clutch_size, fill = larval_treatment)) +
    geom_jitter(aes(color = larval_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    scale_x_discrete(
        limits = levels(results$larval_treatment),
        drop = FALSE) +
     coord_cartesian(ylim = c(0, 400)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
    geom_vline(xintercept = 2.5, linetype = "dashed", color = "black") +
    theme_bw() +
    theme(legend.position = "none") +
   geom_point(aes(x = "warm", y = 109),
               shape = 8, size = 5, colour = "black",
               inherit.aes = FALSE) +
   geom_point(aes(x = "hot", y = 138),
               shape = 8, size = 5, colour = "black",
               inherit.aes = FALSE) +
    labs(
      x = "resource acquisition temperature",
      y = "clutch size (number of eggs)",
      title = paste("")
    )
```

```{r}
larval_temp_warmhot <- results %>% 
  filter(larval_treatment %in% c("warm", "hot"))

ggplot(larval_temp_warmhot,
    aes(x = pupal_treatment, y = clutch_size, fill = pupal_treatment)) +
    geom_jitter(aes(color = pupal_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    scale_x_discrete(
        limits = levels(results$pupal_treatment),
        drop = FALSE) +
     coord_cartesian(ylim = c(0, 400)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(
      x = "pupal temperature",
      y = "clutch size",
      title = paste("warm or hot larval temperature")
    )


```










