---
title: "hatch dates"
output: html_document
---

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(patchwork)
```



```{r}
caterpillar_data <- read.csv(here("data", "clean data", "caterpillar_data.csv"))

#caterpillar_data <- caterpillar_data %>%
  #filter(!is.na(hatch_date)) 

caterpillar_data$pupal_treatment <- as.factor(caterpillar_data$pupal_treatment)
caterpillar_data$hatch_date <- as.Date(caterpillar_data$hatch_date)
caterpillar_data$weight_1 <- as.numeric(caterpillar_data$weight_1)
caterpillar_data$weight_2 <- as.numeric(caterpillar_data$weight_2)

#turn all weights into mg
caterpillar_data$weight_1 <- caterpillar_data$weight_1 * 1000
caterpillar_data$weight_2 <- caterpillar_data$weight_2 * 1000
caterpillar_data$weight3 <- caterpillar_data$weight3 * 1000
caterpillar_data$weight4 <- caterpillar_data$weight4 * 1000
caterpillar_data$weight_5 <- caterpillar_data$weight_5 * 1000

```

```{r}

caterpillar_data <- caterpillar_data %>%
  filter(!is.na(hatched))
  
#how many caterpillars hatches overall
caterpillar_data %>%
  filter(hatched == 1)

hatching_plot <- ggplot(caterpillar_data, aes(x = factor(hatched, labels = c("Unhatched", "Hatched")), y = size_01)) +
  geom_boxplot(width = 0.3, outlier.shape = NA) +
  geom_jitter(width = 0.1, alpha = 0.25, size = 5) +
  #scale_colour_manual(values = temp_cols) +
  labs(x = "", y = expression(Egg~area~(mm^2)), title = "A) Hatching success", colour = "Allocation temperature") +
  theme_bw() +
    theme(
    text = element_text(size = 18),            # increases all text
    axis.title = element_text(size = 20),      # axis titles bigger
    axis.text = element_text(size = 18),       # axis tick labels bigger
    legend.text = element_text(size = 18),     # legend text bigger
    legend.title = element_text(size = 20),
    #legend.position = c(0.98, 0.9),   # top-right inside
  #legend.justification = c(1, 1),     # anchor legend box to its top-right corner
  #legend.background = element_rect(fill = "white", colour = "black")  # optional: improve visibility
    )

hatching_plot

ggsave(
  here("figures", "hatching success.png"),
  plot = hatching_plot,
  width = 10,
  height = 5,
  dpi = 300
)



```
```{r}

caterpillar_size <- ggplot(caterpillar_data, aes(x = size_01, y = weight_1)) +
  geom_point(size = 3) +
  labs(y = "Mass at 18 days post hatching (g)", x = expression(Egg~area~(mm^2)), title = "B) Larval mass") +
  theme_bw() +
    theme(
    text = element_text(size = 18),            # increases all text
    axis.title = element_text(size = 20),      # axis titles bigger
    axis.text = element_text(size = 18),       # axis tick labels bigger
    legend.text = element_text(size = 18),     # legend text bigger
    legend.title = element_text(size = 20)
    )

caterpillar_size


```

```{r}

names(caterpillar_data) <- names(caterpillar_data) %>%
  gsub("^weight([0-9]+)$", "weight_\\1", .)

long_data <- caterpillar_data %>%
  mutate(id = row_number()) %>%
  pivot_longer(
    cols = matches("^(weight|weighday)_\\d+$"),
    names_to = c(".value", "time"),
    names_pattern = "(weight|weighday)_(\\d+)"
  )

long_data$weighday <- as.Date(long_data$weighday)

long_data <- long_data %>%
  mutate(days_post_hatch = as.numeric(weighday - hatch_date)) %>%
  filter(!is.na("weight"))



#random intercepts and random slopes
#model <- lmer(weight ~ days_post_hatch * size_01 + pupal_treatment + (1 | clutchID) + (days_post_hatch | eggID), data = long_data)

#random intercepts only
#model <- lmer(weight ~ days_post_hatch * size_01 + pupal_treatment + (1 | clutchID/eggID), data = long_data)
#ummary(model)

#another option - different slopes per treatment, not per individual caterpillar. seems better.
model <- lmer(weight ~ days_post_hatch * size_01 + days_post_hatch * pupal_treatment + (1|clutchID/eggID), data = long_data)

summary(model)

ggplot(long_data, aes(days_post_hatch, weight, colour = pupal_treatment)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal()

temp_cols <- c(
  ambient = "#484A4C",
  cool    = "#76C0CC",
  mean    = "#F9CA0F",
  warm    = "#E87A36",
  hot     = "#AF0808")




ggplot(long_data, aes(x = weighday, y = weight, group = id)) +
  geom_line(alpha = 0.5) +
  geom_point() +
  labs(x = "Day", y = "Weight", title = "Caterpillar growth over time") +
  theme_minimal()

growth_rate <- ggplot(long_data, aes(x = days_post_hatch, y = weight, group = id, colour = pupal_treatment)) +
  geom_line(alpha = 0.5, size = 1) +
  geom_point(size = 5) +
  scale_x_continuous(breaks = c(18, 24, 30)) +
  labs(x = "Days post hatching", y = "Larval mass (mg)",
       title = "B) Larval growth rate", colour = "Allocation temperature") +
  scale_color_manual(values = temp_cols) +
  theme_bw() +
    theme(
    text = element_text(size = 18),            # increases all text
    axis.title = element_text(size = 20),      # axis titles bigger
    axis.text = element_text(size = 18),       # axis tick labels bigger
    legend.text = element_text(size = 18),     # legend text bigger
    legend.title = element_text(size = 20),
    legend.position = c(0.98, 0.98),   # top-right inside
  legend.justification = c(1, 1),     # anchor legend box to its top-right corner
  legend.background = element_rect(fill = "white", colour = "black")  # optional: improve visibility
    )
growth_rate


caterpillar_plot <-  hatching_plot + growth_rate

ggsave(
  here("figures", "caterpillar plot.png"),
  plot = caterpillar_plot,
  width = 20,
  height = 10,
  dpi = 300
)

```
