---
title: "repeatability individual eggs"
output: html_document
---
```{r}
library(irr)
library(here)
library(dplyr)
```


```{r}
egg_spreadsheet <- read.csv(here("data", "raw data", "eggs spreadsheet.csv"))
```

```{r}
repeatability_data <- egg_spreadsheet %>%
  filter(!is.na(size_02))
  

 
#look at the repeatability of two different photographs of the same eggs
ggplot(repeatability_data, aes(x = size_01, y = size_02)) +
  geom_point() +
  geom_abline( intercept = 0, slope = 1) +
  scale_y_continuous(limits = c(0.16, 0.27)) +
  scale_x_continuous(limits = c(0.16, 0.27)) +
  labs( x = "photograph 1", y = "photograph 2")

#get the r-squared
cor(repeatability_data$size_01, repeatability_data$size_02, use = "complete.obs")


```

```{r}
icc(repeatability_data[, c(5,7)], model="twoway", type="agreement", unit="single")
```
```{r}
results <- read.csv(here("data", "clean data", "results.csv"))

repeatability_results <- results %>%
  filter(!is.na(egg_mean_1B)) %>%
  filter(clutch_code != "8425") %>%
  filter(clutch_code != "7800")

#repeatability between two photographs of the same set of ten eggs
icc(repeatability_results[, c(16,19)], model="twoway", type="agreement", unit="single")



#repeatability between two photographs of different sets of 10 eggs
icc(repeatability_results[, c(17,19)], model="twoway", type="agreement", unit="single")
```



