---
title: "Recycling bin"
output: html_document
---
CLUTCH SIZE FIGURES
```{r}
larval_temp_ambient <- ggplot(
  results %>% filter(larval_treatment == "ambient"),
  aes(x = pupal_treatment, y = clutch_size, fill = pupal_treatment)
) +
  geom_jitter(aes(color = pupal_treatment),
              width = 0.15, size = 2, alpha = 0.8) +
  geom_boxplot(alpha = 0.5, width = 0.7) +
   geom_vline(xintercept = 2.5, linetype = "dashed", color = "black") +
  coord_cartesian(ylim = c(0, 400)) +
  scale_x_discrete(
    limits = levels(results$pupal_treatment),
    drop = FALSE
  ) +
  scale_fill_manual(values = temp_cols) +
  scale_color_manual(values = temp_cols) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    x = "Pupal temperature",
    y = "Clutch size (number of eggs)",
    title = "Larval temperature: ambient OR wild") +
  #overlay wild data
  geom_jitter(
    data = results %>% 
      filter(larval_treatment == "wild"),
    aes(x = pupal_treatment, y = clutch_size),
    inherit.aes = FALSE,
    color = "#D0CDCE",
    width = 0.15,
    size = 2,
    alpha = 0.8) +
  geom_boxplot(
    data = results %>% filter(larval_treatment == "wild"),
    aes(x = pupal_treatment, y = clutch_size),
    inherit.aes = FALSE,
    fill = "#D0CDCE",
    alpha = 0.3,
    width = 0.7,
    outlier.shape= NA
  )

larval_temp_ambient



```

```{r}

larval_levels <- c("cool", "mean", "warm", "hot")

plots <- lapply(larval_levels, function(lt) {

  ggplot(
    results %>% 
    filter(larval_treatment == lt),
    aes(x = pupal_treatment, y = clutch_size, fill = pupal_treatment)) +
    geom_jitter(aes(color = pupal_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape= NA) +
    geom_vline(xintercept = 2.5, linetype = "dashed", color = "black") +
    scale_x_discrete(
        limits = levels(results$pupal_treatment),
        drop = FALSE) +
     coord_cartesian(ylim = c(0, 400)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(
      x = "Pupal temperature",
      y = "Clutch size (number of eggs)",
      title = paste("Larval temperature:", lt)
    )
})

all_plots <- c(list(larval_temp_ambient), plots)

clutch_size_and_temp <- wrap_plots(all_plots, ncol = 3)

ggsave(
  here("figures", "clutch size and temp.png"),
  plot = clutch_size_and_temp,
  width = 20,
  height = 10,
  dpi = 300
)



# View first plot
plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]




```


```{r}
larval_temp_warmhot <- results %>% 
  filter(larval_treatment %in% c("warm", "hot"))

ggplot(larval_temp_warmhot,
    aes(x = pupal_treatment, y = clutch_size, fill = pupal_treatment)) +
    geom_jitter(aes(color = pupal_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    scale_x_discrete(
        limits = levels(results$pupal_treatment),
        drop = FALSE) +
     coord_cartesian(ylim = c(0, 400)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(
      x = "pupal temperature",
      y = "clutch size",
      title = paste("warm or hot larval temperature")
    )


```


EGG SIZE
```{r}
#ambient and wild plot
larval_temp_ambient <- ggplot(
  results %>% filter(larval_treatment == "ambient"),
  aes(x = pupal_treatment, y = egg_mean_1A, fill = pupal_treatment)) +
  geom_jitter(aes(color = pupal_treatment),
              width = 0.15, size = 2, alpha = 0.8) +
  geom_boxplot(alpha = 0.5, width = 0.7, outlier.shape = NA) +
  scale_y_continuous(limits = c(0.15, 0.27)) +
  geom_vline(xintercept = 2.5, linetype = "dashed", color = "black") +
  scale_x_discrete(
    limits = levels(results$pupal_treatment),
    drop = FALSE) +
  scale_fill_manual(values = temp_cols) +
  scale_color_manual(values = temp_cols) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(
    x = "Resource allocation temperature",
    y = expression(Mean~egg~area~(mm^2)),
    title = "ambient or wild acquisition temperature") +
  #overlay wild data
  geom_jitter(
    data = results %>% 
      filter(larval_treatment == "wild"),
    aes(x = pupal_treatment, y = egg_mean_1A),
    inherit.aes = FALSE,
    color = "#D0CDCE",
    width = 0.15,
    size = 2,
    alpha = 0.8) +
  geom_boxplot(
    data = results %>% filter(larval_treatment == "wild"),
    aes(x = pupal_treatment, y = egg_mean_1A),
    inherit.aes = FALSE,
    fill = "#D0CDCE",
    alpha = 0.3,
    width = 0.7,
    outlier.shape = NA
  ) 

larval_temp_ambient

#add significance stars, using values from model
larval_temp_ambient +
  geom_signif(
    comparisons = comparisons,
    annotations = c("**", "**", "***"),
    y_position = c(0.24, 0.245, 0.25),
    textsize = 5,
     vjust = 0.56,
    tip_length = 0.01
  )




#convert the pupal temperatures to factors so they plot in the correct order
results$pupal_treatment <- factor(results$pupal_treatment,
                             levels = c("ambient", "cool", "mean", "warm", "hot"))

#make a separate plot for each larval temperature
larval_levels <- c("cool", "mean", "warm", "hot")

plots <- lapply(larval_levels, function(lt) {

  ggplot(
    results %>% 
    filter(larval_treatment == lt),
    aes(x = pupal_treatment, y = egg_mean_1A, fill = pupal_treatment)
  ) +
    geom_jitter(aes(color = pupal_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    geom_vline(xintercept = 2.5, linetype = "dashed", color = "black") +
    scale_x_discrete(
        limits = levels(results$pupal_treatment),
        drop = FALSE) +
    scale_y_continuous(limits = c(0.15, 0.27)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(
      x = "Pupal temperature",
      y = expression(Mean~egg~area~(mm^2)),
      title = paste("Larval temperature:", lt)
  )
})

all_plots <- c(list(larval_temp_ambient), plots)

egg_size_and_temp <- wrap_plots(all_plots, ncol = 3)

ggsave(
  here("figures", "egg size and temp.png"),
  plot = egg_size_and_temp,
  width = 20,
  height = 10,
  dpi = 300
)



# View first plot
plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]



```

```{r}

#convert the pupal temperatures to factors so they plot in the correct order
results$larval_treatment <- factor(results$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))
larval_temp_warmhot <- results %>% 
  filter(larval_treatment %in% c("wild", "ambient", "warm", "hot"))

ggplot(larval_temp_warmhot,
    aes(x = larval_treatment, y = egg_mean_1A, fill = pupal_treatment)) +
    geom_jitter(aes(color = pupal_treatment),
                width = 0.15, size = 2, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    scale_x_discrete(
        limits = levels(results$larval_treatment),
        drop = FALSE) +
  scale_y_continuous(limits = c(0.16, 0.27)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
  geom_vline(xintercept = 2.5, linetype = "dashed", color = "black") +
    theme_bw() +
    theme(legend.position = "none") +
    labs(
      x = "Resource acquisition temperature",
      y = expression(Mean~egg~area~(mm^2)),
      title = paste("")
    )
```