---
title: "modelling mean egg size"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(lme4)
library(emmeans)
library(lmerTest)
```

```{r}
results <- read.csv(here("data", "clean data", "results.csv"), colClasses = c(sex = "character"))

#make maternal ID a factor
results$maternalID <- as.factor(results$maternalID)



results_filtered <- results %>%
  filter(
    larval_treatment %in% c("ambient", "warm", "hot")) %>%
  filter(clutch_size != 0) %>%
  filter(!is.na(egg_mean_1A)) %>%
  mutate(weight_mg = weight * 1000) %>%
  mutate(weight_mg_centered = weight_mg - mean(weight_mg, na.rm = TRUE)) %>%
  mutate(across(
    c(weight_mg, egg_mean_1A, clutch_size),
    ~ as.numeric(scale(.)),
    .names = "{.col}_z"
  ))

results_filtered <- results_filtered %>%
  mutate(
    larval_treatment = factor(larval_treatment, levels = c("ambient", "warm","hot")),
    pupal_treatment = factor(pupal_treatment, levels = c("ambient", "cool","mean","warm","hot"))
  )
```

```{r}
lm4 <- lmer(egg_mean_1A ~ larval_treatment * pupal_treatment + (1|maternalID) + weight_mg_centered, data = results_filtered)
summary(lm4)

lm4_no_interaction <- lmer(egg_mean_1A ~ larval_treatment + pupal_treatment + (1|maternalID) + weight_mg_centered, data = results_filtered)
anova(lm4, lm4_no_interaction)

lm4_no_larval <- lmer(egg_mean_1A ~ pupal_treatment + (1|maternalID) + weight_mg_centered, data = results_filtered)
anova(lm4_no_interaction, lm4_no_larval)
```

