---
title: "clutch codes"
output: html_document
---
generating clutch codes for the egg images in groups of 10

```{r}
#generate 1000 random 4-digit numbers, with no repeats

set.seed(123)  # optional, for reproducibility
numbers <- sample(1000:9999, 1000)

```

```{r}
#to view it as one column
df <- data.frame(numbers)

```

generating the clutch codes for the egg images of individual eggs

```{r}
#generate 200 random 3-digit numbers, with no repeats

set.seed(120)  # optional, for reproducibility
numbers_for_individual_eggs <- sample(100:999, 200)

#to view it as one column
numbers_for_individual_eggs <- data.frame(numbers_for_individual_eggs)

```

to make the barcodes

```{r}
egg_spreadsheet <- read.csv(here("data", "raw data", "eggs spreadsheet.csv"))

egg_spreadsheet$eggID <- gsub("_", ".", egg_spreadsheet$eggID)

egg_spreadsheet$eggID <- paste0("*", egg_spreadsheet$eggID, "*")

write.csv(egg_spreadsheet, file = here("data", "clean data", "egg spreadsheet.csv"), row.names = FALSE)
```

