---
title: "models"
output: html_document
---

```{r}
library(tidyverse)
library(lme4)
```

```{r}
#read in the mean results, with the clutch codes and the clutch IDs
results <- read.csv(here("data", "results.csv"))

#remove the egg_mean column, because this is the mean egg size from the first round of measure - not interested in this
results <- results %>%
  select(-egg_mean)


#read in the raw results for the third round of measurements
third_raw_results <- read.csv(here("data", "raw results - third time.csv"))

#create the column of unique_egg_ID
third_raw_results <- third_raw_results %>%
   mutate(unique_egg_ID = paste0(clutch_code, "_", egg_number)) %>%
  select(clutch_code, unique_egg_ID, volume)

#now join the two datasets together
merged_results <- results %>%
  left_join(third_raw_results, by = "clutch_code")



```

```{r}
#now i can run my models
lm1 <- lmer(volume ~ pupal_temp + larval_temp + female_mass + (1|clutch_ID) + (1|maternal_clutch), data = merged_results)
  
summary(lm1)

confint(lm1)

anova(lm1)
```




