---
title: "plotting 2.0"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(lme4)
```

```{r}
egg_counts <- read.csv(here("data", "emergence_egg_counts(Sheet1).csv"))


egg_counts$green_eggs  <- as.numeric(egg_counts$green_eggs)
egg_counts$orange_eggs <- as.numeric(egg_counts$orange_eggs)


egg_counts_clean <- egg_counts %>%
  filter(sex == "F") %>% #only looking at females
  filter(!startsWith(adultID, "F")) %>% #remove sienna's females
  mutate(clutch_size = green_eggs + orange_eggs) %>%
  filter(!is.na(clutch_size)) %>% #remove those with NA clutch size
  mutate(larval_treatment = str_extract(adultID, "^[^.]+")) %>% #make larval treatment column
  mutate(
    larval_treatment = recode(
      larval_treatment,
      CTRL = "ambient",
      MEAN = "mean",
      COOL = "cool",
      WARM = "warm",
      HOT  = "hot"
    ))
```

```{r}
#convert the pupal temperatures to factors
egg_counts_clean$pupal_treatment <- factor(egg_counts_clean$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#convert the larval  temperatures to factors
egg_counts_clean$larval_treatment <- factor(egg_counts_clean$larval_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#assign colours to the temperatures                           
temp_cols <- c(
  wild = "#D0CDCE",
  ambient = "#484A4C",
  cool    = "#76C0CC",
  mean    = "#F9CA0F",
  warm    = "#E87A36",
  hot     = "#AF0808")

ggplot(egg_counts_clean, aes(x = pupal_treatment, y = clutch_size, fill = pupal_treatment)) +
  geom_jitter(aes(color = pupal_treatment, shape = larval_treatment), width = 0.15, size = 2, alpha = 0.8) +
  geom_boxplot(alpha = 0.5) +
  scale_x_discrete(labels = levels(factor(egg_counts_clean$pupal_treatment))) +
  scale_fill_manual(values = temp_cols) +
  scale_color_manual(values = temp_cols) + 
  theme_minimal() +
  theme(legend.position = "right") +
  labs(x = "larval temperature", y = "Clutch size (number of eggs)", title = "")
```

