---
title: "trade-off"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(lme4)
library(ggdist)
```


```{r}
#read in the results data
results <- read.csv(here("data", "clean data", "results.csv"))


#convert the pupal temperatures to factors so they plot in the correct order
results$pupal_treatment <- factor(results$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#convert the larval  temperatures to factors so the plot in the correct order
results$larval_treatment <- factor(results$larval_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#assign colours to the temperatures                           
temp_cols <- c(
  ambient = "#484A4C",
  cool    = "#76C0CC",
  mean    = "#F9CA0F",
  warm    = "#E87A36",
  hot     = "#AF0808")


```

```{r}
trade_off_plot <- 
ggplot(results, aes(x = egg_mean_1A, y = clutch_size, fill = pupal_treatment)) +
  geom_point(aes(color = pupal_treatment), alpha = 1.5) +
  scale_color_manual(values = temp_cols) +
  facet_wrap(~ larval_treatment + pupal_treatment) +
    labs(
      x = "egg size (mm)",
      y = "clutch size")

trade_off_plot

ggsave(
  here("figures", "trade_off_plot.png"),
  plot = trade_off_plot,
  width = 17,
  height = 10,
  dpi = 300
)




```