---
title: "plotting mean egg size"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(lme4)
library(ggdist)
library(patchwork)
library(ggsignif)
library(patchwork)
```

EGG SIZE 
```{r}
#read in the results data
results <- read.csv(here("data", "clean data", "results.csv"))


#convert the pupal temperatures to factors so they plot in the correct order
results$pupal_treatment <- factor(results$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#convert the larval  temperatures to factors so the plot in the correct order
results$larval_treatment <- factor(results$larval_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#assign colours to the temperatures                           
temp_cols <- c(
  ambient = "#484A4C",
  cool    = "#76C0CC",
  mean    = "#F9CA0F",
  warm    = "#E87A36",
  hot     = "#AF0808")



```


REPEATABILITY 
```{r}

repeatability_data <- results %>%
  filter(!is.na(egg_mean_2A)) %>%
  filter(!clutch_code %in% c(7800, 8425)) #remove these two rows where I made mistakes in repeatability photos
  


#look at the repeatability of two different photographs of the same eggs
ggplot(repeatability_data, aes(x = egg_mean_1A, y = egg_mean_1B)) +
  geom_point() +
  geom_abline( intercept = 0, slope = 1) +
  scale_y_continuous(limits = c(0.16, 0.27)) +
  scale_x_continuous(limits = c(0.16, 0.27)) +
  annotate("text",
           x = 0.17, y = 0.26,
           label = "R² = 0.92",
           size = 5) +
  labs( x = "photograph 1", y = "photograph 2")
#get the r-squared
cor(repeatability_data$egg_mean_1A, repeatability_data$egg_mean_1B, use = "complete.obs")


#compare the mean of one set of 10 eggs, and then a different set of 10 eggs
ggplot(repeatability_data, aes(x = egg_mean_1A, y = egg_mean_2A)) +
  geom_point() +
  geom_abline( intercept = 0, slope = 1) +
  scale_y_continuous(limits = c(0.16, 0.27)) +
  scale_x_continuous(limits = c(0.16, 0.27)) +
  annotate("text",
           x = 0.17, y = 0.26,
           label = "R² = 0.81",
           size = 5) +
  labs( x = "first set of 10 eggs", y = "different set of 10 eggs")
#get the r-squared
cor(repeatability_data$egg_mean_1A, repeatability_data$egg_mean_2A, use = "complete.obs")

```


```{r}

#convert the pupal temperatures to factors so they plot in the correct order
results$pupal_treatment <- factor(results$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))
larval_temp_warmhot <- results %>% 
  filter(larval_treatment %in% c("wild", "ambient", "warm", "hot"))

mean_egg_size <- ggplot(results,
    aes(x = pupal_treatment, y = egg_mean_1A, fill = pupal_treatment)) +
    geom_jitter(aes(color = pupal_treatment),
                width = 0.15, size = 4, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    scale_x_discrete(
        limits = levels(results$pupal_treatment),
        drop = FALSE) +
  scale_y_continuous(breaks = seq(0.14, 0.29, by = 0.02)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
   geom_vline(xintercept = 2.5, linetype = "dashed", size = 1.5, color = "black") +
    theme_bw() +
    theme(legend.position = "none") +
    labs(
      x = "Resource allocation temperature",
      y = expression(Mean~egg~area~(mm^2)),
      title = paste("A) Observed mean egg size")
    ) +
    theme(
    text = element_text(size = 18),            # increases all text
    axis.title = element_text(size = 20),      # axis titles bigger
    axis.text = element_text(size = 18),       # axis tick labels bigger
    legend.text = element_text(size = 18),     # legend text bigger
    legend.title = element_text(size = 20)
    )

mean_egg_size


egg_size <- mean_egg_size + egg_size_model

ggsave(
  here("figures", "egg_size.png"),
  plot = egg_size,
  width = 20,
  height = 10,
  dpi = 300
)
```





