---
title: "clutch size"
output: html_document
---

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(patchwork)
library(ggdist)
```


```{r}
#read in the results data
results <- read.csv(here("data", "clean data", "results.csv"))


#convert the pupal temperatures to factors so they plot in the correct order
results$pupal_treatment <- factor(results$pupal_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#convert the larval  temperatures to factors so the plot in the correct order
results$larval_treatment <- factor(results$larval_treatment,
                             levels = c("wild", "ambient", "cool", "mean", "warm", "hot"))

#assign colours to the temperatures                           
temp_cols <- c(
  ambient = "#484A4C",
  cool    = "#76C0CC",
  mean    = "#F9CA0F",
  warm    = "#E87A36",
  hot     = "#AF0808")

#remove clutches of 0 eggs
results <- results %>%
  filter(clutch_size != 0)

```


```{r}

#Make clutch size figure
clutch_size_plot <- ggplot(results,
    aes(x = larval_treatment, y = clutch_size, fill = larval_treatment)) +
    geom_jitter(aes(color = larval_treatment),
                width = 0.15, size = 4, alpha = 0.8) +
    geom_boxplot(alpha = 0.5, outlier.shape = NA) +
    scale_x_discrete(
        limits = levels(results$larval_treatment),
        drop = FALSE) +
     coord_cartesian(ylim = c(0, 400)) +
    scale_fill_manual(values = temp_cols) +
    scale_color_manual(values = temp_cols) +
    geom_vline(xintercept = 2.5, linetype = "dashed", size = 1.5, color = "black") +
    theme_bw() +
    theme(legend.position = "none") +
   geom_point(aes(x = "warm", y = 109),
               shape = 8, size = 8, colour = "black",
               inherit.aes = FALSE) +
   geom_point(aes(x = "hot", y = 138),
               shape = 8, size = 8, colour = "black",
               inherit.aes = FALSE) +
    labs(
      x = "Resource acquisition temperature",
      y = "Clutch size (number of eggs)",
      title = paste("A) Observed clutch size")
    ) +
    theme(
    text = element_text(size = 18),            # increases all text
    axis.title = element_text(size = 20),      # axis titles bigger
    axis.text = element_text(size = 18),       # axis tick labels bigger
    legend.text = element_text(size = 18),     # legend text bigger
    legend.title = element_text(size = 20)
    )

clutch_size_plot



sem_plot <- clutch_size_plot + sem_predictions

ggsave(
  here("figures", "sem plot.png"),
  plot = sem_plot,
  width = 20,
  height = 10,
  dpi = 300
)
```












