---
title: "calculatin mean temp in each treatment"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(here)
library(car)
library(lubridate)
```

```{r}
ambient_temperatures <- read.csv(here("data", "clean data", "ambient temperatures.csv"))

ambient_temperatures$datetime <- parse_date_time(
  ambient_temperatures$datetime,
  orders = c("ymd HMS", "ymd"),
  tz = "UTC"
)

#filter for one day earlier so can have delta T for all days
#filter the ambient temperatures for the whole period of resource acquisition and allocation
ambient_temperatures <- ambient_temperatures %>%
  filter(
    datetime >= as.POSIXct("2025-03-11 00:00:00", tz = "UTC"),
    datetime <= as.POSIXct("2025-12-29 23:50:00", tz = "UTC")
  )

#to get the mean temp in ambient during the acquisition period
ambient_acquisition_period <- ambient_temperatures %>%
  filter(datetime >= as.POSIXct("2025-04-11 00:00:00") &
         datetime <= as.POSIXct("2025-05-16 23:59:59"))
mean(ambient_acquisition_period$temperature)
#12.36538


#to get the mean temp in ambient during the allocation period
ambient_allocation_period <- ambient_temperatures %>%
  filter(datetime >= as.POSIXct("2025-05-16 00:00:00") &
         datetime <= as.POSIXct("2025-12-29 23:59:59"))
mean(ambient_allocation_period$temperature)
#14.34


#get the daily mean temperature
ambient_daily_means <- ambient_temperatures %>%
  mutate(date = as.Date(datetime)) %>%   # extract date
  group_by(date) %>%
  summarise(mean_temp = mean(temperature, na.rm = TRUE))


#calculate the change in daily mean temperature from one day to the next
ambient_daily_means <- ambient_daily_means %>%
  arrange(date) %>%   # make sure it's in chronological order
  mutate(temp_change = mean_temp - lag(mean_temp))
```



```{r}
incubator_treatments <- read.csv(here("data", "raw data", "mbiols_daily_temperature_data.csv"))

#to make sure dates are stored as dates, and temperatures as numbers
incubator_treatments <- incubator_treatments %>%
  mutate(
    date_1   = as.Date(date_1, format = "%d/%m/%Y"),
    date_end = as.Date(date_end, format = "%d/%m/%Y"),
    `plus2.5`    = as.numeric(`plus2.5`),
    `plus1.5`    = as.numeric(`plus1.5`),
    `actual.mean` = as.numeric(`actual.mean`),
    `minus1.5`   = as.numeric(`minus1.5`),
    `minus2.5`   = as.numeric(`minus2.5`)
  )

#combine date 1 and date end into one date column
incubator_treatments <- incubator_treatments %>%
  group_by(date_1, date_end, Hour_group) %>%
   pivot_longer(
    cols = c(date_1, date_end),
    names_to = "date_type",
    values_to = "date") %>%
  dplyr::select(-date_type) 




#get the mean in each incubator treatment during acquisition period
acquisition_incubator_period <- incubator_treatments %>%
  filter(date >= as.Date("2025-04-11") & date <= as.Date("2025-05-16"))

mean(acquisition_incubator_period$minus1.5)
#8.37

mean(acquisition_incubator_period$actual.mean)
#10.10

mean(acquisition_incubator_period$plus1.5)
#11.84

mean(acquisition_incubator_period$plus2.5)
#12.99


#get the mean of each incubator treatment duirng the allocation period
allocation_incubator_period <- incubator_treatments %>%
  filter(date >= as.Date("2025-05-16") & date <= as.Date("2025-12-29"))

mean(allocation_incubator_period$minus1.5)
#10.22

mean(allocation_incubator_period$actual.mean)
#12.21

mean(allocation_incubator_period$plus1.5)
#14.19

mean(allocation_incubator_period$plus2.5)
#15.51





#calcluate the daily mean temp for each incubator treatment
incubator_daily_means <- incubator_treatments %>%
  group_by(date) %>%
  summarise(
    across(c(plus2.5, plus1.5, actual.mean, minus1.5),
           ~ mean(.x, na.rm = TRUE))
  )


incubator_daily_means <- incubator_daily_means %>%
  mutate(
    temp_change_plus2.5 = `plus2.5` - lag(`plus2.5`),
    temp_change_plus1.5 = `plus1.5` - lag(`plus1.5`),
    temp_change_actual.mean = `actual.mean` - lag(`actual.mean`),
    temp_change_minus1.5 = `minus1.5` - lag(`minus1.5`)
  )

```

RESOURCE ACQUISITION
```{r}
#dataset for period of resource alocation - using median pupation date and median emergence date

acquisition_ambient_temp <- ambient_daily_means %>%
  filter(date >= as.Date("2025-04-11") & date <= as.Date("2025-05-16"))

mean(acquisition_ambient_temp$temp_change, na.rm = TRUE)
#0.14

sd(acquisition_ambient_temp$temp_change, na.rm = TRUE)
#1.48




acquisition_incubator_temp <- incubator_daily_means %>%
  filter(date >= as.Date("2025-04-11") & date <= as.Date("2025-05-16"))




mean(acquisition_incubator_temp$temp_change_minus1.5, na.rm = TRUE)
#0.13
sd(acquisition_incubator_temp$temp_change_minus1.5, na.rm = TRUE)
#0.3


mean(acquisition_incubator_temp$temp_change_actual.mean, na.rm = TRUE)
sd(acquisition_incubator_temp$temp_change_actual.mean, na.rm = TRUE)
#0.28


mean(acquisition_incubator_temp$temp_change_plus1.5)
#0.12
sd(acquisition_incubator_temp$temp_change_plus1.5)
#0.27

mean(acquisition_incubator_temp$temp_change_plus2.5)
#0.11
sd(acquisition_incubator_temp$temp_change_plus2.5)
#0.27

```

RESOURCE ALLOCATION
```{r}
#dataset for period of resource acquisition - using median halfhatch date and median pupation date
allocation_ambient_temp <- ambient_daily_means %>%
  filter(date >= as.Date("2025-05-16") & date <= as.Date("2025-12-29"))



mean(allocation_ambient_temp$temp_change)
#-0.03

sd(allocation_ambient_temp$temp_change)
#1.72



allocation_incubator_temp <- incubator_daily_means %>%
  filter(date >= as.Date("2025-05-16") & date <= as.Date("2025-12-29"))


mean(allocation_incubator_temp$temp_change_minus1.5)
#-0.04
sd(allocation_incubator_temp$temp_change_minus1.5)
#0.26



mean(allocation_incubator_temp$temp_change_actual.mean)
#0.039
sd(allocation_incubator_temp$temp_change_actual.mean)
#0.26



mean(allocation_incubator_temp$temp_change_plus1.5)
#-0.035
sd(allocation_incubator_temp$temp_change_plus1.5)
#0.26


mean(allocation_incubator_temp$temp_change_plus2.5)
sd(allocation_incubator_temp$temp_change_plus2.5)
#0.28

```

